services:
  - type: web
    name: livebetting-tracker-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web.web:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - fromDotEnv: true

  - type: worker
    name: livebetting-tracker-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python worker/main.py
    autoDeploy: true
    envVars:
      - fromDotEnv: true
