services:
  - type: web
    name: flask-betting-tracker
    env: python
    buildCommand: ""
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 main:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
